
Hi, thanks for visiting! I am a self-proclaimed baking enthusiast who has been learning how to cook since moving away from home in 2018. 

Some of my recipes are from the internet; others have been passed down from family and friends! 

## Desserts

* [Fudgy Brownies](desserts/brownies.html)
* [Chocolate Chip Cookes](desserts/choc_chip_cookies.html)
* [5-minute Microwave Mug Brownie](desserts/mug_brownie.html)
* [Chocolate Fudge](desserts/fudge.html)
* [Banana Bread](https://sallysbakingaddiction.com/best-banana-bread-recipe/)
* [Xander's Dark Chocolate Tart](https://www.joyousapron.com/no-bake-chocolate-tart/#recipe) but instead of the berries, top with a homemade [Caramel Sauce](https://sallysbakingaddiction.com/homemade-salted-caramel-recipe/)
* [Apple Crumble](desserts/apple_crumble.html)

## Other baked goods

* [Focaccia](https://www.youtube.com/shorts/bmO6CIOrDEU?si=4mHCY9K-x_3Hv9xy)

## Coffee + its accessories 

* [Vanilla Simple Syrup](coffee-accessories/vanilla_simple_syrup.html)
* [Lavender Simple Syrup](https://www.thespruceeats.com/diy-lavender-simple-syrup-760293)
* [Dalgona Coffee (South Asian Whipped Coffee)](coffee-accessories/dalgona_coffee.html)

## Pakistani food

* "Green" Chicken
* Kari Chawal
* Daal
* Shami Kababs
* Chicken Tikka (for meal-prep)
* [Qeema](pakistani-food/qeema.html)
